name: Backend CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: ./mvnw test

      - name: Get next version
        id: version
        run: |
          git fetch --tags

          LAST_TAG=$(git tag -l "v[0-9]*" | sort -V | tail -n 1)

          if [ -z "$LAST_TAG" ]; then
            NEW_VERSION="v1"
          else
            LAST_NUMBER=${LAST_TAG#v}
            NEW_NUMBER=$((LAST_NUMBER + 1))
            NEW_VERSION="v$NEW_NUMBER"
          fi

          echo "Nueva versión: $NEW_VERSION"
          echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag "${{ steps.version.outputs.version }}"
          git push origin "${{ steps.version.outputs.version }}"

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar-${{ steps.version.outputs.version }}
          path: target/*.jar