name: Backend CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: ./mvnw test

      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Get next version
        id: version
        run: |
          git fetch --tags

          LAST_TAG=$(git tag --sort=-v:refname | head -n 1)

          if [ -z "$LAST_TAG" ]; then
            NEW_VERSION="v1.0.0"
          else
            VERSION=${LAST_TAG#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            PATCH=$((PATCH + 1))
            NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          fi

          echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
          echo "Nueva versión: $NEW_VERSION"

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar-${{ steps.version.outputs.version }}
          path: target/*.jar